// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyFriends.Data;

#nullable disable

namespace MyFriends.Data.Migrations
{
    [DbContext(typeof(MyFriendsContext))]
    partial class MyFriendsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("MyFriends.Models.Friend", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Age");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Friends");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 25,
                            Name = "John"
                        },
                        new
                        {
                            Id = 2,
                            Age = 19,
                            Name = "Peter"
                        },
                        new
                        {
                            Id = 3,
                            Age = 32,
                            Name = "Sam"
                        },
                        new
                        {
                            Id = 4,
                            Age = 40,
                            Name = "Michael"
                        },
                        new
                        {
                            Id = 5,
                            Age = 20,
                            Name = "Peppa"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
